package com.jantztechnologies.ride;

// Literally the only reason this class exists is to avoid cluttering up MainActivity with arrays
//      holding ints referencing drawables. I was originally using AnimationDrawables, but CERTAIN
//      DEVICES don't have enough %$*^@ing RAM to hold all four animationDrawables simultaneously... so this
//      is the workaround.
public class TitleScreenAnimationArrays {
    private int[] rDrawables;
    private int[] iDrawables;
    private int[] dDrawables;
    private int[] eDrawables;

    public TitleScreenAnimationArrays() {
        fillRDrawablesArray();
        fillIDrawablesArray();
        fillDDrawablesArray();
        fillEDrawablesArray();
    }

    // 69 drawables, counting those commented out
    // 40 drawables, excluding those commented out
    private void fillRDrawablesArray() {
        rDrawables = new int[]{
                //R.drawable.frame000,
                R.drawable.frame001,
                R.drawable.frame002,
                R.drawable.frame003,
                //R.drawable.frame004,
                R.drawable.frame005,
                R.drawable.frame006,
                R.drawable.frame007,
                //R.drawable.frame008,
                R.drawable.frame009,
                R.drawable.frame010,
                //R.drawable.frame011,
                R.drawable.frame012,
                //R.drawable.frame013,
                R.drawable.frame014,
                //R.drawable.frame015,
                R.drawable.frame016,
                //R.drawable.frame017,
                R.drawable.frame018,
                //R.drawable.frame019,
                R.drawable.frame020,
                //R.drawable.frame021,
                R.drawable.frame022,
                //R.drawable.frame023,
                R.drawable.frame024,
                //R.drawable.frame025,
                R.drawable.frame026,
                //R.drawable.frame027,
                R.drawable.frame028,
                //R.drawable.frame029,
                R.drawable.frame030,
                //R.drawable.frame031,
                R.drawable.frame032,
                //R.drawable.frame033,
                R.drawable.frame034,
                //R.drawable.frame035,
                R.drawable.frame036,
                //R.drawable.frame037,
                R.drawable.frame038,
                //R.drawable.frame039,
                R.drawable.frame040,
                //R.drawable.frame041,
                R.drawable.frame042,
                //R.drawable.frame043,
                R.drawable.frame044,
                //R.drawable.frame045,
                R.drawable.frame046,
                //R.drawable.frame047,
                R.drawable.frame048,
                //R.drawable.frame049,
                R.drawable.frame050,
                //R.drawable.frame051,
                R.drawable.frame052,
                //R.drawable.frame053,
                R.drawable.frame054,
                //R.drawable.frame055,
                R.drawable.frame056,
                //R.drawable.frame057,
                R.drawable.frame058,
                R.drawable.frame059,
                //R.drawable.frame060,
                R.drawable.frame061,
                R.drawable.frame062,
                R.drawable.frame063,
                //R.drawable.frame064,
                R.drawable.frame065,
                R.drawable.frame066,
                R.drawable.frame067,
                R.drawable.frame068,
        };
    }

    // 40 drawables, counting those commented out
    private void fillIDrawablesArray() {
        iDrawables = new int[]{
                R.drawable.frame069,
                R.drawable.frame070,
                R.drawable.frame071,
                R.drawable.frame072,
                R.drawable.frame073,
                R.drawable.frame074,
                R.drawable.frame075,
                R.drawable.frame076,
                R.drawable.frame077,
                R.drawable.frame078,
                R.drawable.frame079,
                R.drawable.frame080,
                R.drawable.frame081,
                R.drawable.frame082,
                R.drawable.frame083,
                R.drawable.frame084,
                R.drawable.frame085,
                R.drawable.frame086,
                R.drawable.frame087,
                R.drawable.frame088,
                R.drawable.frame089,
                R.drawable.frame090,
                R.drawable.frame091,
                R.drawable.frame092,
                R.drawable.frame093,
                R.drawable.frame094,
                R.drawable.frame095,
                R.drawable.frame096,
                R.drawable.frame097,
                R.drawable.frame098,
                R.drawable.frame099,
                R.drawable.frame100,
                R.drawable.frame101,
                R.drawable.frame102,
                R.drawable.frame103,
                R.drawable.frame104,
                R.drawable.frame105,
                R.drawable.frame106,
                R.drawable.frame107,
                R.drawable.frame108,
        };
    }

    // 53 drawables, counting those commented out
    // 40 drawables, excluding those commented out
    private void fillDDrawablesArray() {
        dDrawables = new int[]{
                R.drawable.frame109,
                R.drawable.frame110,
                R.drawable.frame111,
                R.drawable.frame112,
                R.drawable.frame113,
                R.drawable.frame114,
                //R.drawable.frame115,
                R.drawable.frame116,
                R.drawable.frame117,
                R.drawable.frame118,
                R.drawable.frame119,
                //R.drawable.frame120,
                R.drawable.frame121,
                R.drawable.frame122,
                R.drawable.frame123,
                //R.drawable.frame124,
                R.drawable.frame125,
                R.drawable.frame126,
                //R.drawable.frame127,
                R.drawable.frame128,
                R.drawable.frame129,
                //R.drawable.frame130,
                R.drawable.frame131,
                R.drawable.frame132,
                //R.drawable.frame133,
                R.drawable.frame134,
                //R.drawable.frame135,
                R.drawable.frame136,
                //R.drawable.frame137,
                R.drawable.frame138,
                R.drawable.frame139,
                //R.drawable.frame140,
                R.drawable.frame141,
                R.drawable.frame142,
                //R.drawable.frame143,
                R.drawable.frame144,
                R.drawable.frame145,
                //R.drawable.frame146,
                R.drawable.frame147,
                R.drawable.frame148,
                R.drawable.frame149,
                //R.drawable.frame150,
                R.drawable.frame151,
                R.drawable.frame152,
                R.drawable.frame153,
                R.drawable.frame154,
                //R.drawable.frame155,
                R.drawable.frame156,
                R.drawable.frame157,
                R.drawable.frame158,
                R.drawable.frame159,
                R.drawable.frame160,
                R.drawable.frame161,
        };
    }

    // 94 drawables, counting those commented out
    // 40 drawables, excluding those commented out
    private void fillEDrawablesArray() {
        eDrawables = new int[]{
                R.drawable.frame162,
                R.drawable.frame163,
                //R.drawable.frame164,
                R.drawable.frame165,
                //R.drawable.frame166,
                R.drawable.frame167,
                //R.drawable.frame168,
                R.drawable.frame169,
                //R.drawable.frame170,
                R.drawable.frame171,
                //R.drawable.frame172,
                //R.drawable.frame173,
                R.drawable.frame174,
                //R.drawable.frame175,
                R.drawable.frame176,
                //R.drawable.frame177,
                R.drawable.frame178,
                //R.drawable.frame179,
                R.drawable.frame180,
                //R.drawable.frame181,
                //R.drawable.frame182,
                R.drawable.frame183,
                //R.drawable.frame184,
                R.drawable.frame185,
                //R.drawable.frame186,
                R.drawable.frame187,
                //R.drawable.frame188,
                //R.drawable.frame189,
                R.drawable.frame190,
                //R.drawable.frame191,
                R.drawable.frame192,
                //R.drawable.frame193,
                //R.drawable.frame194,
                R.drawable.frame195,
                //R.drawable.frame196,
                //R.drawable.frame197,
                R.drawable.frame198,
                //R.drawable.frame199,
                //R.drawable.frame200,
                R.drawable.frame201,
                //R.drawable.frame202,
                //R.drawable.frame203,
                R.drawable.frame204,
                //R.drawable.frame205,
                //R.drawable.frame206,
                R.drawable.frame207,
                //R.drawable.frame208,
                //R.drawable.frame209,
                R.drawable.frame210,
                //R.drawable.frame211,
                //R.drawable.frame212,
                R.drawable.frame213,
                //R.drawable.frame214,
                //R.drawable.frame215,
                R.drawable.frame216,
                //R.drawable.frame217,
                //R.drawable.frame218,
                R.drawable.frame219,
                //R.drawable.frame220,
                //R.drawable.frame221,
                R.drawable.frame222,
                //R.drawable.frame223,
                //R.drawable.frame224,
                R.drawable.frame225,
                //R.drawable.frame226,
                R.drawable.frame227,
                //R.drawable.frame228,
                //R.drawable.frame229,
                R.drawable.frame230,
                //R.drawable.frame231,
                R.drawable.frame232,
                //R.drawable.frame233,
                R.drawable.frame234,
                //R.drawable.frame235,
                //R.drawable.frame236,
                R.drawable.frame237,
                //R.drawable.frame238,
                R.drawable.frame239,
                //R.drawable.frame240,
                R.drawable.frame241,
                //R.drawable.frame242,
                R.drawable.frame243,
                //R.drawable.frame244,
                //R.drawable.frame245,
                R.drawable.frame246,
                //R.drawable.frame247,
                R.drawable.frame248,
                //R.drawable.frame249,
                R.drawable.frame250,
                //R.drawable.frame251,
                R.drawable.frame252,
                //R.drawable.frame253,
                R.drawable.frame254,
                R.drawable.frame255,
        };
    }

    public int getRDrawableAtIndex(int index) {
        return rDrawables[index];
    }

    public int getIDrawableAtIndex(int index) {
        return iDrawables[index];
    }

    public int getDDrawableAtIndex(int index) {
        return dDrawables[index];
    }

    public int getEDrawableAtIndex(int index) {
        return eDrawables[index];
    }
}
